apiVersion: v1
entries:
  parent-blockfinder:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2023-09-28T01:20:57.959421841+05:30"
    dependencies:
    - name: blockfenderscharts
      repository: https://dutta249.github.io/helm-charts/charts
      version: 0.2.0
    description: A Helm chart for parent-blockfinder demo microservice
    digest: 6f5e705ff326018570154cda4a314b218a88c60d1aacd79ca1486f449695f811
    name: parent-blockfinder
    type: application
    urls:
    - parent-blockfinder-0.1.0.tgz
    version: 0.1.0
generated: "2023-09-28T01:20:57.956133843+05:30"
